/**
 * Twelve Data API client for Go
 *
 * NOTE: This code is auto generated, please do not edit it manually.
 */
package twelvedata

import (
	"encoding/json"
)

// checks if the CashFlowStructOperatingActivities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CashFlowStructOperatingActivities{}

// CashFlowStructOperatingActivities Operating activities section
type CashFlowStructOperatingActivities struct {
	// Returns net income (NI). Calculated as sales minus cost of goods sold
	NetIncome *float64 `json:"net_income,omitempty"`
	// Represents depreciation and amortization measure
	Depreciation *float64 `json:"depreciation,omitempty"`
	// Stands for taxes that are owed but are not due to be paid until a future date
	DeferredTaxes *float64 `json:"deferred_taxes,omitempty"`
	// Refers to share-based compensation as the way of paying employees, executives, and directors of a company with equity in the business
	StockBasedCompensation *float64 `json:"stock_based_compensation,omitempty"`
	// Represents other non-cash items
	OtherNonCashItems *float64 `json:"other_non_cash_items,omitempty"`
	// Represents the balance of money due to a firm for goods or services delivered or used but not yet paid for by customers
	AccountsReceivable *float64 `json:"accounts_receivable,omitempty"`
	// Refers to an account within the general ledger that represents an obligation to pay off a short-term debt to creditors or suppliers
	AccountsPayable *float64 `json:"accounts_payable,omitempty"`
	// Represents cumulative changes in inventory, other current assets, other current liabilities, and other working capital
	OtherAssetsLiabilities *float64 `json:"other_assets_liabilities,omitempty"`
	// Returns operating cash flow (OCF) measure representing a total amount of cash generated by company's normal business operations
	OperatingCashFlow *float64 `json:"operating_cash_flow,omitempty"`
}

// NewCashFlowStructOperatingActivities instantiates a new CashFlowStructOperatingActivities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCashFlowStructOperatingActivities() *CashFlowStructOperatingActivities {
	this := CashFlowStructOperatingActivities{}
	return &this
}

// NewCashFlowStructOperatingActivitiesWithDefaults instantiates a new CashFlowStructOperatingActivities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCashFlowStructOperatingActivitiesWithDefaults() *CashFlowStructOperatingActivities {
	this := CashFlowStructOperatingActivities{}
	return &this
}

// GetNetIncome returns the NetIncome field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetNetIncome() float64 {
	if o == nil || IsNil(o.NetIncome) {
		var ret float64
		return ret
	}
	return *o.NetIncome
}

// GetNetIncomeOk returns a tuple with the NetIncome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetNetIncomeOk() (*float64, bool) {
	if o == nil || IsNil(o.NetIncome) {
		return nil, false
	}
	return o.NetIncome, true
}

// HasNetIncome returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasNetIncome() bool {
	if o != nil && !IsNil(o.NetIncome) {
		return true
	}

	return false
}

// SetNetIncome gets a reference to the given float64 and assigns it to the NetIncome field.
func (o *CashFlowStructOperatingActivities) SetNetIncome(v float64) {
	o.NetIncome = &v
}

// GetDepreciation returns the Depreciation field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetDepreciation() float64 {
	if o == nil || IsNil(o.Depreciation) {
		var ret float64
		return ret
	}
	return *o.Depreciation
}

// GetDepreciationOk returns a tuple with the Depreciation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetDepreciationOk() (*float64, bool) {
	if o == nil || IsNil(o.Depreciation) {
		return nil, false
	}
	return o.Depreciation, true
}

// HasDepreciation returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasDepreciation() bool {
	if o != nil && !IsNil(o.Depreciation) {
		return true
	}

	return false
}

// SetDepreciation gets a reference to the given float64 and assigns it to the Depreciation field.
func (o *CashFlowStructOperatingActivities) SetDepreciation(v float64) {
	o.Depreciation = &v
}

// GetDeferredTaxes returns the DeferredTaxes field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetDeferredTaxes() float64 {
	if o == nil || IsNil(o.DeferredTaxes) {
		var ret float64
		return ret
	}
	return *o.DeferredTaxes
}

// GetDeferredTaxesOk returns a tuple with the DeferredTaxes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetDeferredTaxesOk() (*float64, bool) {
	if o == nil || IsNil(o.DeferredTaxes) {
		return nil, false
	}
	return o.DeferredTaxes, true
}

// HasDeferredTaxes returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasDeferredTaxes() bool {
	if o != nil && !IsNil(o.DeferredTaxes) {
		return true
	}

	return false
}

// SetDeferredTaxes gets a reference to the given float64 and assigns it to the DeferredTaxes field.
func (o *CashFlowStructOperatingActivities) SetDeferredTaxes(v float64) {
	o.DeferredTaxes = &v
}

// GetStockBasedCompensation returns the StockBasedCompensation field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetStockBasedCompensation() float64 {
	if o == nil || IsNil(o.StockBasedCompensation) {
		var ret float64
		return ret
	}
	return *o.StockBasedCompensation
}

// GetStockBasedCompensationOk returns a tuple with the StockBasedCompensation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetStockBasedCompensationOk() (*float64, bool) {
	if o == nil || IsNil(o.StockBasedCompensation) {
		return nil, false
	}
	return o.StockBasedCompensation, true
}

// HasStockBasedCompensation returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasStockBasedCompensation() bool {
	if o != nil && !IsNil(o.StockBasedCompensation) {
		return true
	}

	return false
}

// SetStockBasedCompensation gets a reference to the given float64 and assigns it to the StockBasedCompensation field.
func (o *CashFlowStructOperatingActivities) SetStockBasedCompensation(v float64) {
	o.StockBasedCompensation = &v
}

// GetOtherNonCashItems returns the OtherNonCashItems field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetOtherNonCashItems() float64 {
	if o == nil || IsNil(o.OtherNonCashItems) {
		var ret float64
		return ret
	}
	return *o.OtherNonCashItems
}

// GetOtherNonCashItemsOk returns a tuple with the OtherNonCashItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetOtherNonCashItemsOk() (*float64, bool) {
	if o == nil || IsNil(o.OtherNonCashItems) {
		return nil, false
	}
	return o.OtherNonCashItems, true
}

// HasOtherNonCashItems returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasOtherNonCashItems() bool {
	if o != nil && !IsNil(o.OtherNonCashItems) {
		return true
	}

	return false
}

// SetOtherNonCashItems gets a reference to the given float64 and assigns it to the OtherNonCashItems field.
func (o *CashFlowStructOperatingActivities) SetOtherNonCashItems(v float64) {
	o.OtherNonCashItems = &v
}

// GetAccountsReceivable returns the AccountsReceivable field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetAccountsReceivable() float64 {
	if o == nil || IsNil(o.AccountsReceivable) {
		var ret float64
		return ret
	}
	return *o.AccountsReceivable
}

// GetAccountsReceivableOk returns a tuple with the AccountsReceivable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetAccountsReceivableOk() (*float64, bool) {
	if o == nil || IsNil(o.AccountsReceivable) {
		return nil, false
	}
	return o.AccountsReceivable, true
}

// HasAccountsReceivable returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasAccountsReceivable() bool {
	if o != nil && !IsNil(o.AccountsReceivable) {
		return true
	}

	return false
}

// SetAccountsReceivable gets a reference to the given float64 and assigns it to the AccountsReceivable field.
func (o *CashFlowStructOperatingActivities) SetAccountsReceivable(v float64) {
	o.AccountsReceivable = &v
}

// GetAccountsPayable returns the AccountsPayable field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetAccountsPayable() float64 {
	if o == nil || IsNil(o.AccountsPayable) {
		var ret float64
		return ret
	}
	return *o.AccountsPayable
}

// GetAccountsPayableOk returns a tuple with the AccountsPayable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetAccountsPayableOk() (*float64, bool) {
	if o == nil || IsNil(o.AccountsPayable) {
		return nil, false
	}
	return o.AccountsPayable, true
}

// HasAccountsPayable returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasAccountsPayable() bool {
	if o != nil && !IsNil(o.AccountsPayable) {
		return true
	}

	return false
}

// SetAccountsPayable gets a reference to the given float64 and assigns it to the AccountsPayable field.
func (o *CashFlowStructOperatingActivities) SetAccountsPayable(v float64) {
	o.AccountsPayable = &v
}

// GetOtherAssetsLiabilities returns the OtherAssetsLiabilities field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetOtherAssetsLiabilities() float64 {
	if o == nil || IsNil(o.OtherAssetsLiabilities) {
		var ret float64
		return ret
	}
	return *o.OtherAssetsLiabilities
}

// GetOtherAssetsLiabilitiesOk returns a tuple with the OtherAssetsLiabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetOtherAssetsLiabilitiesOk() (*float64, bool) {
	if o == nil || IsNil(o.OtherAssetsLiabilities) {
		return nil, false
	}
	return o.OtherAssetsLiabilities, true
}

// HasOtherAssetsLiabilities returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasOtherAssetsLiabilities() bool {
	if o != nil && !IsNil(o.OtherAssetsLiabilities) {
		return true
	}

	return false
}

// SetOtherAssetsLiabilities gets a reference to the given float64 and assigns it to the OtherAssetsLiabilities field.
func (o *CashFlowStructOperatingActivities) SetOtherAssetsLiabilities(v float64) {
	o.OtherAssetsLiabilities = &v
}

// GetOperatingCashFlow returns the OperatingCashFlow field value if set, zero value otherwise.
func (o *CashFlowStructOperatingActivities) GetOperatingCashFlow() float64 {
	if o == nil || IsNil(o.OperatingCashFlow) {
		var ret float64
		return ret
	}
	return *o.OperatingCashFlow
}

// GetOperatingCashFlowOk returns a tuple with the OperatingCashFlow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CashFlowStructOperatingActivities) GetOperatingCashFlowOk() (*float64, bool) {
	if o == nil || IsNil(o.OperatingCashFlow) {
		return nil, false
	}
	return o.OperatingCashFlow, true
}

// HasOperatingCashFlow returns a boolean if a field has been set.
func (o *CashFlowStructOperatingActivities) HasOperatingCashFlow() bool {
	if o != nil && !IsNil(o.OperatingCashFlow) {
		return true
	}

	return false
}

// SetOperatingCashFlow gets a reference to the given float64 and assigns it to the OperatingCashFlow field.
func (o *CashFlowStructOperatingActivities) SetOperatingCashFlow(v float64) {
	o.OperatingCashFlow = &v
}

func (o CashFlowStructOperatingActivities) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CashFlowStructOperatingActivities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetIncome) {
		toSerialize["net_income"] = o.NetIncome
	}
	if !IsNil(o.Depreciation) {
		toSerialize["depreciation"] = o.Depreciation
	}
	if !IsNil(o.DeferredTaxes) {
		toSerialize["deferred_taxes"] = o.DeferredTaxes
	}
	if !IsNil(o.StockBasedCompensation) {
		toSerialize["stock_based_compensation"] = o.StockBasedCompensation
	}
	if !IsNil(o.OtherNonCashItems) {
		toSerialize["other_non_cash_items"] = o.OtherNonCashItems
	}
	if !IsNil(o.AccountsReceivable) {
		toSerialize["accounts_receivable"] = o.AccountsReceivable
	}
	if !IsNil(o.AccountsPayable) {
		toSerialize["accounts_payable"] = o.AccountsPayable
	}
	if !IsNil(o.OtherAssetsLiabilities) {
		toSerialize["other_assets_liabilities"] = o.OtherAssetsLiabilities
	}
	if !IsNil(o.OperatingCashFlow) {
		toSerialize["operating_cash_flow"] = o.OperatingCashFlow
	}
	return toSerialize, nil
}

type NullableCashFlowStructOperatingActivities struct {
	value *CashFlowStructOperatingActivities
	isSet bool
}

func (v NullableCashFlowStructOperatingActivities) Get() *CashFlowStructOperatingActivities {
	return v.value
}

func (v *NullableCashFlowStructOperatingActivities) Set(val *CashFlowStructOperatingActivities) {
	v.value = val
	v.isSet = true
}

func (v NullableCashFlowStructOperatingActivities) IsSet() bool {
	return v.isSet
}

func (v *NullableCashFlowStructOperatingActivities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCashFlowStructOperatingActivities(val *CashFlowStructOperatingActivities) *NullableCashFlowStructOperatingActivities {
	return &NullableCashFlowStructOperatingActivities{value: val, isSet: true}
}

func (v NullableCashFlowStructOperatingActivities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCashFlowStructOperatingActivities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
