// Twelve Data API client for Go
//
// NOTE: This code is auto generated, please do not edit it manually.

package twelvedata

import (
	"encoding/json"
)

// checks if the GetMutualFundsWorld200ResponseMutualFundSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMutualFundsWorld200ResponseMutualFundSummary{}

// GetMutualFundsWorld200ResponseMutualFundSummary A brief summary of a mutual fund
type GetMutualFundsWorld200ResponseMutualFundSummary struct {
	// All available fund types segmented by country
	Symbol *string `json:"symbol,omitempty"`
	// Fund name
	Name *string `json:"name,omitempty"`
	// Investment company that manages the fund
	FundFamily *string `json:"fund_family,omitempty"`
	// Type of the fund
	FundType *string `json:"fund_type,omitempty"`
	// Currency of fund price
	Currency *string `json:"currency,omitempty"`
	// The date from which the fund started operations and the returns are calculated
	ShareClassInceptionDate *string `json:"share_class_inception_date,omitempty"`
	// Percentage of profit of the fund since the first trading day of the current calendar year
	YtdReturn *float64 `json:"ytd_return,omitempty"`
	// Percentage of mutual fund assets steered toward a fund's operating expenses and fund management fees
	ExpenseRatioNet *float64 `json:"expense_ratio_net,omitempty"`
	// Income returned to its investors through interest and dividends generated by the fund's investments
	Yield *float64 `json:"yield,omitempty"`
	// Net Asset Value: fund value minus liabilities
	Nav *float64 `json:"nav,omitempty"`
	// Investment minimum
	MinInvestment *int64 `json:"min_investment,omitempty"`
	// Percentage rate at which mutual fund replaces its holdings on investment every year
	TurnoverRate *float64 `json:"turnover_rate,omitempty"`
	// Total assets of a fund minus its total liabilities
	NetAssets *int64 `json:"net_assets,omitempty"`
	// Description of the fund
	Overview *string `json:"overview,omitempty"`
	// Information about the fund’s managers
	People []GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner `json:"people,omitempty"`
}

// NewGetMutualFundsWorld200ResponseMutualFundSummary instantiates a new GetMutualFundsWorld200ResponseMutualFundSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMutualFundsWorld200ResponseMutualFundSummary() *GetMutualFundsWorld200ResponseMutualFundSummary {
	this := GetMutualFundsWorld200ResponseMutualFundSummary{}
	return &this
}

// NewGetMutualFundsWorld200ResponseMutualFundSummaryWithDefaults instantiates a new GetMutualFundsWorld200ResponseMutualFundSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMutualFundsWorld200ResponseMutualFundSummaryWithDefaults() *GetMutualFundsWorld200ResponseMutualFundSummary {
	this := GetMutualFundsWorld200ResponseMutualFundSummary{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetSymbol(v string) {
	o.Symbol = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetName(v string) {
	o.Name = &v
}

// GetFundFamily returns the FundFamily field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetFundFamily() string {
	if o == nil || IsNil(o.FundFamily) {
		var ret string
		return ret
	}
	return *o.FundFamily
}

// GetFundFamilyOk returns a tuple with the FundFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetFundFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.FundFamily) {
		return nil, false
	}
	return o.FundFamily, true
}

// HasFundFamily returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasFundFamily() bool {
	if o != nil && !IsNil(o.FundFamily) {
		return true
	}

	return false
}

// SetFundFamily gets a reference to the given string and assigns it to the FundFamily field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetFundFamily(v string) {
	o.FundFamily = &v
}

// GetFundType returns the FundType field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetFundType() string {
	if o == nil || IsNil(o.FundType) {
		var ret string
		return ret
	}
	return *o.FundType
}

// GetFundTypeOk returns a tuple with the FundType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetFundTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FundType) {
		return nil, false
	}
	return o.FundType, true
}

// HasFundType returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasFundType() bool {
	if o != nil && !IsNil(o.FundType) {
		return true
	}

	return false
}

// SetFundType gets a reference to the given string and assigns it to the FundType field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetFundType(v string) {
	o.FundType = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetCurrency(v string) {
	o.Currency = &v
}

// GetShareClassInceptionDate returns the ShareClassInceptionDate field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetShareClassInceptionDate() string {
	if o == nil || IsNil(o.ShareClassInceptionDate) {
		var ret string
		return ret
	}
	return *o.ShareClassInceptionDate
}

// GetShareClassInceptionDateOk returns a tuple with the ShareClassInceptionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetShareClassInceptionDateOk() (*string, bool) {
	if o == nil || IsNil(o.ShareClassInceptionDate) {
		return nil, false
	}
	return o.ShareClassInceptionDate, true
}

// HasShareClassInceptionDate returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasShareClassInceptionDate() bool {
	if o != nil && !IsNil(o.ShareClassInceptionDate) {
		return true
	}

	return false
}

// SetShareClassInceptionDate gets a reference to the given string and assigns it to the ShareClassInceptionDate field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetShareClassInceptionDate(v string) {
	o.ShareClassInceptionDate = &v
}

// GetYtdReturn returns the YtdReturn field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetYtdReturn() float64 {
	if o == nil || IsNil(o.YtdReturn) {
		var ret float64
		return ret
	}
	return *o.YtdReturn
}

// GetYtdReturnOk returns a tuple with the YtdReturn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetYtdReturnOk() (*float64, bool) {
	if o == nil || IsNil(o.YtdReturn) {
		return nil, false
	}
	return o.YtdReturn, true
}

// HasYtdReturn returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasYtdReturn() bool {
	if o != nil && !IsNil(o.YtdReturn) {
		return true
	}

	return false
}

// SetYtdReturn gets a reference to the given float64 and assigns it to the YtdReturn field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetYtdReturn(v float64) {
	o.YtdReturn = &v
}

// GetExpenseRatioNet returns the ExpenseRatioNet field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetExpenseRatioNet() float64 {
	if o == nil || IsNil(o.ExpenseRatioNet) {
		var ret float64
		return ret
	}
	return *o.ExpenseRatioNet
}

// GetExpenseRatioNetOk returns a tuple with the ExpenseRatioNet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetExpenseRatioNetOk() (*float64, bool) {
	if o == nil || IsNil(o.ExpenseRatioNet) {
		return nil, false
	}
	return o.ExpenseRatioNet, true
}

// HasExpenseRatioNet returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasExpenseRatioNet() bool {
	if o != nil && !IsNil(o.ExpenseRatioNet) {
		return true
	}

	return false
}

// SetExpenseRatioNet gets a reference to the given float64 and assigns it to the ExpenseRatioNet field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetExpenseRatioNet(v float64) {
	o.ExpenseRatioNet = &v
}

// GetYield returns the Yield field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetYield() float64 {
	if o == nil || IsNil(o.Yield) {
		var ret float64
		return ret
	}
	return *o.Yield
}

// GetYieldOk returns a tuple with the Yield field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetYieldOk() (*float64, bool) {
	if o == nil || IsNil(o.Yield) {
		return nil, false
	}
	return o.Yield, true
}

// HasYield returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasYield() bool {
	if o != nil && !IsNil(o.Yield) {
		return true
	}

	return false
}

// SetYield gets a reference to the given float64 and assigns it to the Yield field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetYield(v float64) {
	o.Yield = &v
}

// GetNav returns the Nav field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetNav() float64 {
	if o == nil || IsNil(o.Nav) {
		var ret float64
		return ret
	}
	return *o.Nav
}

// GetNavOk returns a tuple with the Nav field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetNavOk() (*float64, bool) {
	if o == nil || IsNil(o.Nav) {
		return nil, false
	}
	return o.Nav, true
}

// HasNav returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasNav() bool {
	if o != nil && !IsNil(o.Nav) {
		return true
	}

	return false
}

// SetNav gets a reference to the given float64 and assigns it to the Nav field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetNav(v float64) {
	o.Nav = &v
}

// GetMinInvestment returns the MinInvestment field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetMinInvestment() int64 {
	if o == nil || IsNil(o.MinInvestment) {
		var ret int64
		return ret
	}
	return *o.MinInvestment
}

// GetMinInvestmentOk returns a tuple with the MinInvestment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetMinInvestmentOk() (*int64, bool) {
	if o == nil || IsNil(o.MinInvestment) {
		return nil, false
	}
	return o.MinInvestment, true
}

// HasMinInvestment returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasMinInvestment() bool {
	if o != nil && !IsNil(o.MinInvestment) {
		return true
	}

	return false
}

// SetMinInvestment gets a reference to the given int64 and assigns it to the MinInvestment field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetMinInvestment(v int64) {
	o.MinInvestment = &v
}

// GetTurnoverRate returns the TurnoverRate field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetTurnoverRate() float64 {
	if o == nil || IsNil(o.TurnoverRate) {
		var ret float64
		return ret
	}
	return *o.TurnoverRate
}

// GetTurnoverRateOk returns a tuple with the TurnoverRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetTurnoverRateOk() (*float64, bool) {
	if o == nil || IsNil(o.TurnoverRate) {
		return nil, false
	}
	return o.TurnoverRate, true
}

// HasTurnoverRate returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasTurnoverRate() bool {
	if o != nil && !IsNil(o.TurnoverRate) {
		return true
	}

	return false
}

// SetTurnoverRate gets a reference to the given float64 and assigns it to the TurnoverRate field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetTurnoverRate(v float64) {
	o.TurnoverRate = &v
}

// GetNetAssets returns the NetAssets field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetNetAssets() int64 {
	if o == nil || IsNil(o.NetAssets) {
		var ret int64
		return ret
	}
	return *o.NetAssets
}

// GetNetAssetsOk returns a tuple with the NetAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetNetAssetsOk() (*int64, bool) {
	if o == nil || IsNil(o.NetAssets) {
		return nil, false
	}
	return o.NetAssets, true
}

// HasNetAssets returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasNetAssets() bool {
	if o != nil && !IsNil(o.NetAssets) {
		return true
	}

	return false
}

// SetNetAssets gets a reference to the given int64 and assigns it to the NetAssets field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetNetAssets(v int64) {
	o.NetAssets = &v
}

// GetOverview returns the Overview field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetOverview() string {
	if o == nil || IsNil(o.Overview) {
		var ret string
		return ret
	}
	return *o.Overview
}

// GetOverviewOk returns a tuple with the Overview field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetOverviewOk() (*string, bool) {
	if o == nil || IsNil(o.Overview) {
		return nil, false
	}
	return o.Overview, true
}

// HasOverview returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasOverview() bool {
	if o != nil && !IsNil(o.Overview) {
		return true
	}

	return false
}

// SetOverview gets a reference to the given string and assigns it to the Overview field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetOverview(v string) {
	o.Overview = &v
}

// GetPeople returns the People field value if set, zero value otherwise.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetPeople() []GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner {
	if o == nil || IsNil(o.People) {
		var ret []GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner
		return ret
	}
	return o.People
}

// GetPeopleOk returns a tuple with the People field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) GetPeopleOk() ([]GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner, bool) {
	if o == nil || IsNil(o.People) {
		return nil, false
	}
	return o.People, true
}

// HasPeople returns a boolean if a field has been set.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) HasPeople() bool {
	if o != nil && !IsNil(o.People) {
		return true
	}

	return false
}

// SetPeople gets a reference to the given []GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner and assigns it to the People field.
func (o *GetMutualFundsWorld200ResponseMutualFundSummary) SetPeople(v []GetMutualFundsWorld200ResponseMutualFundSummaryPeopleInner) {
	o.People = v
}

func (o GetMutualFundsWorld200ResponseMutualFundSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMutualFundsWorld200ResponseMutualFundSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.FundFamily) {
		toSerialize["fund_family"] = o.FundFamily
	}
	if !IsNil(o.FundType) {
		toSerialize["fund_type"] = o.FundType
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.ShareClassInceptionDate) {
		toSerialize["share_class_inception_date"] = o.ShareClassInceptionDate
	}
	if !IsNil(o.YtdReturn) {
		toSerialize["ytd_return"] = o.YtdReturn
	}
	if !IsNil(o.ExpenseRatioNet) {
		toSerialize["expense_ratio_net"] = o.ExpenseRatioNet
	}
	if !IsNil(o.Yield) {
		toSerialize["yield"] = o.Yield
	}
	if !IsNil(o.Nav) {
		toSerialize["nav"] = o.Nav
	}
	if !IsNil(o.MinInvestment) {
		toSerialize["min_investment"] = o.MinInvestment
	}
	if !IsNil(o.TurnoverRate) {
		toSerialize["turnover_rate"] = o.TurnoverRate
	}
	if !IsNil(o.NetAssets) {
		toSerialize["net_assets"] = o.NetAssets
	}
	if !IsNil(o.Overview) {
		toSerialize["overview"] = o.Overview
	}
	if !IsNil(o.People) {
		toSerialize["people"] = o.People
	}
	return toSerialize, nil
}

type NullableGetMutualFundsWorld200ResponseMutualFundSummary struct {
	value *GetMutualFundsWorld200ResponseMutualFundSummary
	isSet bool
}

func (v NullableGetMutualFundsWorld200ResponseMutualFundSummary) Get() *GetMutualFundsWorld200ResponseMutualFundSummary {
	return v.value
}

func (v *NullableGetMutualFundsWorld200ResponseMutualFundSummary) Set(val *GetMutualFundsWorld200ResponseMutualFundSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMutualFundsWorld200ResponseMutualFundSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMutualFundsWorld200ResponseMutualFundSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMutualFundsWorld200ResponseMutualFundSummary(val *GetMutualFundsWorld200ResponseMutualFundSummary) *NullableGetMutualFundsWorld200ResponseMutualFundSummary {
	return &NullableGetMutualFundsWorld200ResponseMutualFundSummary{value: val, isSet: true}
}

func (v NullableGetMutualFundsWorld200ResponseMutualFundSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMutualFundsWorld200ResponseMutualFundSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
