// Twelve Data API client for Go
//
// NOTE: This code is auto generated, please do not edit it manually.

package twelvedata

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetETFsWorld200ResponseEtfSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetETFsWorld200ResponseEtfSummary{}

// GetETFsWorld200ResponseEtfSummary A brief summary of a etf
type GetETFsWorld200ResponseEtfSummary struct {
	// All available fund types segmented by country
	Symbol string `json:"symbol"`
	// Fund name
	Name string `json:"name"`
	// Investment company that manages the fund
	FundFamily *string `json:"fund_family,omitempty"`
	// Type of the fund
	FundType *string `json:"fund_type,omitempty"`
	// Currency of fund price
	Currency *string `json:"currency,omitempty"`
	// The date from which the fund started operations and the returns are calculated
	ShareClassInceptionDate *string `json:"share_class_inception_date,omitempty"`
	// Percentage of profit of the fund since the first trading day of the current calendar year
	YtdReturn *float64 `json:"ytd_return,omitempty"`
	// Percentage of ETF assets steered toward a fund's operating expenses and fund management fees
	ExpenseRatioNet *float64 `json:"expense_ratio_net,omitempty"`
	// Income returned to its investors through interest and dividends generated by the fund's investments
	Yield *float64 `json:"yield,omitempty"`
	// Net Asset Value: fund value minus liabilities
	Nav *float64 `json:"nav,omitempty"`
	// Last price of the fund
	LastPrice *float64 `json:"last_price,omitempty"`
	// Percentage rate at which ETF replaces its holdings on investment every year
	TurnoverRate *float64 `json:"turnover_rate,omitempty"`
	// Total assets of a fund minus its total liabilities
	NetAssets *int64 `json:"net_assets,omitempty"`
	// Description of the fund
	Overview *string `json:"overview,omitempty"`
}

type _GetETFsWorld200ResponseEtfSummary GetETFsWorld200ResponseEtfSummary

// NewGetETFsWorld200ResponseEtfSummary instantiates a new GetETFsWorld200ResponseEtfSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetETFsWorld200ResponseEtfSummary(symbol string, name string) *GetETFsWorld200ResponseEtfSummary {
	this := GetETFsWorld200ResponseEtfSummary{}
	this.Symbol = symbol
	this.Name = name
	return &this
}

// NewGetETFsWorld200ResponseEtfSummaryWithDefaults instantiates a new GetETFsWorld200ResponseEtfSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetETFsWorld200ResponseEtfSummaryWithDefaults() *GetETFsWorld200ResponseEtfSummary {
	this := GetETFsWorld200ResponseEtfSummary{}
	return &this
}

// GetSymbol returns the Symbol field value
func (o *GetETFsWorld200ResponseEtfSummary) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *GetETFsWorld200ResponseEtfSummary) SetSymbol(v string) {
	o.Symbol = v
}

// GetName returns the Name field value
func (o *GetETFsWorld200ResponseEtfSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetETFsWorld200ResponseEtfSummary) SetName(v string) {
	o.Name = v
}

// GetFundFamily returns the FundFamily field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetFundFamily() string {
	if o == nil || IsNil(o.FundFamily) {
		var ret string
		return ret
	}
	return *o.FundFamily
}

// GetFundFamilyOk returns a tuple with the FundFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetFundFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.FundFamily) {
		return nil, false
	}
	return o.FundFamily, true
}

// HasFundFamily returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasFundFamily() bool {
	if o != nil && !IsNil(o.FundFamily) {
		return true
	}

	return false
}

// SetFundFamily gets a reference to the given string and assigns it to the FundFamily field.
func (o *GetETFsWorld200ResponseEtfSummary) SetFundFamily(v string) {
	o.FundFamily = &v
}

// GetFundType returns the FundType field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetFundType() string {
	if o == nil || IsNil(o.FundType) {
		var ret string
		return ret
	}
	return *o.FundType
}

// GetFundTypeOk returns a tuple with the FundType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetFundTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FundType) {
		return nil, false
	}
	return o.FundType, true
}

// HasFundType returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasFundType() bool {
	if o != nil && !IsNil(o.FundType) {
		return true
	}

	return false
}

// SetFundType gets a reference to the given string and assigns it to the FundType field.
func (o *GetETFsWorld200ResponseEtfSummary) SetFundType(v string) {
	o.FundType = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetETFsWorld200ResponseEtfSummary) SetCurrency(v string) {
	o.Currency = &v
}

// GetShareClassInceptionDate returns the ShareClassInceptionDate field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetShareClassInceptionDate() string {
	if o == nil || IsNil(o.ShareClassInceptionDate) {
		var ret string
		return ret
	}
	return *o.ShareClassInceptionDate
}

// GetShareClassInceptionDateOk returns a tuple with the ShareClassInceptionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetShareClassInceptionDateOk() (*string, bool) {
	if o == nil || IsNil(o.ShareClassInceptionDate) {
		return nil, false
	}
	return o.ShareClassInceptionDate, true
}

// HasShareClassInceptionDate returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasShareClassInceptionDate() bool {
	if o != nil && !IsNil(o.ShareClassInceptionDate) {
		return true
	}

	return false
}

// SetShareClassInceptionDate gets a reference to the given string and assigns it to the ShareClassInceptionDate field.
func (o *GetETFsWorld200ResponseEtfSummary) SetShareClassInceptionDate(v string) {
	o.ShareClassInceptionDate = &v
}

// GetYtdReturn returns the YtdReturn field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetYtdReturn() float64 {
	if o == nil || IsNil(o.YtdReturn) {
		var ret float64
		return ret
	}
	return *o.YtdReturn
}

// GetYtdReturnOk returns a tuple with the YtdReturn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetYtdReturnOk() (*float64, bool) {
	if o == nil || IsNil(o.YtdReturn) {
		return nil, false
	}
	return o.YtdReturn, true
}

// HasYtdReturn returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasYtdReturn() bool {
	if o != nil && !IsNil(o.YtdReturn) {
		return true
	}

	return false
}

// SetYtdReturn gets a reference to the given float64 and assigns it to the YtdReturn field.
func (o *GetETFsWorld200ResponseEtfSummary) SetYtdReturn(v float64) {
	o.YtdReturn = &v
}

// GetExpenseRatioNet returns the ExpenseRatioNet field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetExpenseRatioNet() float64 {
	if o == nil || IsNil(o.ExpenseRatioNet) {
		var ret float64
		return ret
	}
	return *o.ExpenseRatioNet
}

// GetExpenseRatioNetOk returns a tuple with the ExpenseRatioNet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetExpenseRatioNetOk() (*float64, bool) {
	if o == nil || IsNil(o.ExpenseRatioNet) {
		return nil, false
	}
	return o.ExpenseRatioNet, true
}

// HasExpenseRatioNet returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasExpenseRatioNet() bool {
	if o != nil && !IsNil(o.ExpenseRatioNet) {
		return true
	}

	return false
}

// SetExpenseRatioNet gets a reference to the given float64 and assigns it to the ExpenseRatioNet field.
func (o *GetETFsWorld200ResponseEtfSummary) SetExpenseRatioNet(v float64) {
	o.ExpenseRatioNet = &v
}

// GetYield returns the Yield field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetYield() float64 {
	if o == nil || IsNil(o.Yield) {
		var ret float64
		return ret
	}
	return *o.Yield
}

// GetYieldOk returns a tuple with the Yield field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetYieldOk() (*float64, bool) {
	if o == nil || IsNil(o.Yield) {
		return nil, false
	}
	return o.Yield, true
}

// HasYield returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasYield() bool {
	if o != nil && !IsNil(o.Yield) {
		return true
	}

	return false
}

// SetYield gets a reference to the given float64 and assigns it to the Yield field.
func (o *GetETFsWorld200ResponseEtfSummary) SetYield(v float64) {
	o.Yield = &v
}

// GetNav returns the Nav field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetNav() float64 {
	if o == nil || IsNil(o.Nav) {
		var ret float64
		return ret
	}
	return *o.Nav
}

// GetNavOk returns a tuple with the Nav field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetNavOk() (*float64, bool) {
	if o == nil || IsNil(o.Nav) {
		return nil, false
	}
	return o.Nav, true
}

// HasNav returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasNav() bool {
	if o != nil && !IsNil(o.Nav) {
		return true
	}

	return false
}

// SetNav gets a reference to the given float64 and assigns it to the Nav field.
func (o *GetETFsWorld200ResponseEtfSummary) SetNav(v float64) {
	o.Nav = &v
}

// GetLastPrice returns the LastPrice field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetLastPrice() float64 {
	if o == nil || IsNil(o.LastPrice) {
		var ret float64
		return ret
	}
	return *o.LastPrice
}

// GetLastPriceOk returns a tuple with the LastPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetLastPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.LastPrice) {
		return nil, false
	}
	return o.LastPrice, true
}

// HasLastPrice returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasLastPrice() bool {
	if o != nil && !IsNil(o.LastPrice) {
		return true
	}

	return false
}

// SetLastPrice gets a reference to the given float64 and assigns it to the LastPrice field.
func (o *GetETFsWorld200ResponseEtfSummary) SetLastPrice(v float64) {
	o.LastPrice = &v
}

// GetTurnoverRate returns the TurnoverRate field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetTurnoverRate() float64 {
	if o == nil || IsNil(o.TurnoverRate) {
		var ret float64
		return ret
	}
	return *o.TurnoverRate
}

// GetTurnoverRateOk returns a tuple with the TurnoverRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetTurnoverRateOk() (*float64, bool) {
	if o == nil || IsNil(o.TurnoverRate) {
		return nil, false
	}
	return o.TurnoverRate, true
}

// HasTurnoverRate returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasTurnoverRate() bool {
	if o != nil && !IsNil(o.TurnoverRate) {
		return true
	}

	return false
}

// SetTurnoverRate gets a reference to the given float64 and assigns it to the TurnoverRate field.
func (o *GetETFsWorld200ResponseEtfSummary) SetTurnoverRate(v float64) {
	o.TurnoverRate = &v
}

// GetNetAssets returns the NetAssets field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetNetAssets() int64 {
	if o == nil || IsNil(o.NetAssets) {
		var ret int64
		return ret
	}
	return *o.NetAssets
}

// GetNetAssetsOk returns a tuple with the NetAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetNetAssetsOk() (*int64, bool) {
	if o == nil || IsNil(o.NetAssets) {
		return nil, false
	}
	return o.NetAssets, true
}

// HasNetAssets returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasNetAssets() bool {
	if o != nil && !IsNil(o.NetAssets) {
		return true
	}

	return false
}

// SetNetAssets gets a reference to the given int64 and assigns it to the NetAssets field.
func (o *GetETFsWorld200ResponseEtfSummary) SetNetAssets(v int64) {
	o.NetAssets = &v
}

// GetOverview returns the Overview field value if set, zero value otherwise.
func (o *GetETFsWorld200ResponseEtfSummary) GetOverview() string {
	if o == nil || IsNil(o.Overview) {
		var ret string
		return ret
	}
	return *o.Overview
}

// GetOverviewOk returns a tuple with the Overview field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetETFsWorld200ResponseEtfSummary) GetOverviewOk() (*string, bool) {
	if o == nil || IsNil(o.Overview) {
		return nil, false
	}
	return o.Overview, true
}

// HasOverview returns a boolean if a field has been set.
func (o *GetETFsWorld200ResponseEtfSummary) HasOverview() bool {
	if o != nil && !IsNil(o.Overview) {
		return true
	}

	return false
}

// SetOverview gets a reference to the given string and assigns it to the Overview field.
func (o *GetETFsWorld200ResponseEtfSummary) SetOverview(v string) {
	o.Overview = &v
}

func (o GetETFsWorld200ResponseEtfSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetETFsWorld200ResponseEtfSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["name"] = o.Name
	if !IsNil(o.FundFamily) {
		toSerialize["fund_family"] = o.FundFamily
	}
	if !IsNil(o.FundType) {
		toSerialize["fund_type"] = o.FundType
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.ShareClassInceptionDate) {
		toSerialize["share_class_inception_date"] = o.ShareClassInceptionDate
	}
	if !IsNil(o.YtdReturn) {
		toSerialize["ytd_return"] = o.YtdReturn
	}
	if !IsNil(o.ExpenseRatioNet) {
		toSerialize["expense_ratio_net"] = o.ExpenseRatioNet
	}
	if !IsNil(o.Yield) {
		toSerialize["yield"] = o.Yield
	}
	if !IsNil(o.Nav) {
		toSerialize["nav"] = o.Nav
	}
	if !IsNil(o.LastPrice) {
		toSerialize["last_price"] = o.LastPrice
	}
	if !IsNil(o.TurnoverRate) {
		toSerialize["turnover_rate"] = o.TurnoverRate
	}
	if !IsNil(o.NetAssets) {
		toSerialize["net_assets"] = o.NetAssets
	}
	if !IsNil(o.Overview) {
		toSerialize["overview"] = o.Overview
	}
	return toSerialize, nil
}

func (o *GetETFsWorld200ResponseEtfSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"symbol",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetETFsWorld200ResponseEtfSummary := _GetETFsWorld200ResponseEtfSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varGetETFsWorld200ResponseEtfSummary)

	if err != nil {
		return err
	}

	*o = GetETFsWorld200ResponseEtfSummary(varGetETFsWorld200ResponseEtfSummary)

	return err
}

type NullableGetETFsWorld200ResponseEtfSummary struct {
	value *GetETFsWorld200ResponseEtfSummary
	isSet bool
}

func (v NullableGetETFsWorld200ResponseEtfSummary) Get() *GetETFsWorld200ResponseEtfSummary {
	return v.value
}

func (v *NullableGetETFsWorld200ResponseEtfSummary) Set(val *GetETFsWorld200ResponseEtfSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGetETFsWorld200ResponseEtfSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGetETFsWorld200ResponseEtfSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetETFsWorld200ResponseEtfSummary(val *GetETFsWorld200ResponseEtfSummary) *NullableGetETFsWorld200ResponseEtfSummary {
	return &NullableGetETFsWorld200ResponseEtfSummary{value: val, isSet: true}
}

func (v NullableGetETFsWorld200ResponseEtfSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetETFsWorld200ResponseEtfSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
